### ISSUE TITLE
Feature: User can get familiar with the app

### ISSUE THREAD

**Issue by Catfishslim** [vcu-cmsc355-f17/android-app-the-four-s#1]
As an app user 
so that I can know how to use the app
I want to see a welcome screen when I open the app

**Comment by Catfishslim** [comment]
given app unopened
when I open the app
I should see an opening splash with the app name

**Comment by Catfishslim** [comment]
given app showing welcome splash
when I view the splash
I should see the app name and info

**Comment by Catfishslim** [comment]
given app showing welcome splash
when I wait two second
I should see the main app view

**Comment by cptwangatang** [comment]
splash screen wait time is 5 seconds
info page directs only to home page

**Comment by cptwangatang** [comment]
**Given** I am on the `App Info` page
**When** I click the `i` icon
**Then** I should be on the `Home` page

**Comment by cptwangatang** [comment]
**Given** I am on the `Welcome` page
**When** I click the app `Logo` of the app `Icon`
**Then** I should be on the `Home` page
