### ISSUE TITLE
Feature: User can use the reward points to upgrade the plant

### ISSUE THREAD

**Issue by Shir0o** [vcu-cmsc355-f17/android-app-the-four-s#4]
As a driver
So that I can be motivated to save fuel
I want to grow my plant using my reward points

**Comment by Shir0o** [comment]
### Scenario: navigate to the `Apply Upgrades` page

**Given** I am on the `Plant` page
**When** I click on the menu icon
**Then** I should see a drop down menu
**When** I click on the `Upgrade` button
**Then** I should be on the `Apply Upgrades` page
**And** I should see my remaining balance of reward points
**And** I should see 2 confirmation buttons labeled with `Yes` and `No`

**Comment by Shir0o** [comment]
### Scenario: navigate to the `Choose Upgrades` page

**Given** I am on the `Apply Upgrades` page
**When** I click on the `Yes` button
**Then** I  should be on the `Choose Upgrades` page
**And** I should see 3 upgrade selections
**And** I should see 2 buttons labeled with `Choose` and `Cancel`

**Comment by Shir0o** [comment]
### Scenario: go back to the `Apply Upgrades` page from the `Choose Upgrades` page

**Given** I am on the `Choose Upgrades` page
**When** I click on one of the options
**Then** The option I have clicked on should be highlighted
**When** I click on the `Cancel` button
**Then** I should be back on the `Apply Upgrades` page

**Comment by Shir0o** [comment]
### Scenario: apply reward points for upgrades

**Given** I am on the `Choose Upgrades` page
**When** I click on one of the options
**Then** The option I have clicked on should be highlighted
**When** I click on the `Choose` button
**Then** I should be on the `Plant` page
**And** I should see my plant being upgraded with the option I have selected

**Comment by Shir0o** [comment]
### Scenario: navigate back to the `Home` page

**Given** I am on the `Upgrade` page
**When** I click on the `Plant` image
**Then** I should be on the `Home` page

**Comment by cptwangatang** [comment]
##Scenario: choosing to not unlock the plant
**Given** I see the dialog confirmation box
**When** I click on the `No` button
**Then** I should be back on the `Upgrade` page
**And** my plant should remain unchanged.
